name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "posts/**"
      - "posts/list.json"
      - "index.html"
      - "CNAME"
  pull_request:
    paths:
      - "posts/**"
      - "posts/list.json"
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # 发布仓库根目录
